import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

/**
 * Generate and download an official HEIMDALL Gate Scan & Hostel Records PDF Report
 *
 * @param {Object} reportData - { metadata, summary, records } from /api/archive/export-data
 * @param {string} fileName - Optional custom file name
 */
export const downloadGateRecordsPDF = (reportData, customFileName) => {
  const { metadata = {}, summary = {}, records = [] } = reportData || {};

  const doc = new jsPDF({
    orientation: 'landscape',
    unit: 'pt',
    format: 'a4',
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  // ── Header Banner ──
  doc.setFillColor(15, 23, 42); // slate-900
  doc.rect(0, 0, pageWidth, 68, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.text('🏛️ HEIMDALL — CAMPUS ACCESS & GATE SCAN REPORT', 40, 32);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9.5);
  doc.setTextColor(148, 163, 184); // slate-400
  doc.text('Indian Institute of Information Technology, Pune (IIIT Pune) — Hostel Management System', 40, 48);

  // ── Report Metadata & Summary Box ──
  const startY = 82;
  doc.setFillColor(248, 250, 252); // slate-50
  doc.setDrawColor(226, 232, 240); // slate-200
  doc.roundedRect(40, startY, pageWidth - 80, 56, 6, 6, 'FD');

  doc.setFontSize(9);
  doc.setTextColor(30, 41, 59);

  // Left column
  doc.setFont('helvetica', 'bold');
  doc.text('Period / Scope:', 54, startY + 20);
  doc.setFont('helvetica', 'normal');
  doc.text(String(metadata.period || 'All Records'), 130, startY + 20);

  doc.setFont('helvetica', 'bold');
  doc.text('Hostel Filter:', 54, startY + 38);
  doc.setFont('helvetica', 'normal');
  doc.text(String(metadata.hostelFilter || 'All Hostels'), 130, startY + 38);

  // Center column
  doc.setFont('helvetica', 'bold');
  doc.text('Generated By:', 260, startY + 20);
  doc.setFont('helvetica', 'normal');
  doc.text(String(metadata.generatedBy || 'Authorized Staff'), 340, startY + 20);

  doc.setFont('helvetica', 'bold');
  doc.text('Generated On:', 260, startY + 38);
  doc.setFont('helvetica', 'normal');
  doc.text(String(metadata.generatedAt || new Date().toLocaleString('en-IN')), 340, startY + 38);

  // Right column (Metrics)
  doc.setFont('helvetica', 'bold');
  doc.text('Total Records:', 520, startY + 20);
  doc.setFont('helvetica', 'normal');
  doc.text(String(summary.totalRecords || records.length), 600, startY + 20);

  doc.setFont('helvetica', 'bold');
  doc.text('Exits / Entries:', 520, startY + 38);
  doc.setFont('helvetica', 'normal');
  doc.text(`${summary.totalExits || 0} Out / ${summary.totalEntries || 0} In`, 600, startY + 38);

  // ── Table ──
  const tableRows = records.map((r, index) => [
    index + 1,
    r.date || '—',
    r.time || '—',
    r.studentName || '—',
    r.rollNo || '—',
    r.hostel || '—',
    r.category || 'In/Out',
    r.status || '—',
    r.returned || '—',
    r.destination || '—',
  ]);

  autoTable(doc, {
    startY: startY + 68,
    margin: { left: 40, right: 40, bottom: 45 },
    head: [[
      '#',
      'Date',
      'Time',
      'Student Name',
      'Roll No',
      'Hostel',
      'Pass Type',
      'Status',
      'Returned',
      'Destination / Reason',
    ]],
    body: tableRows,
    theme: 'grid',
    headStyles: {
      fillColor: [79, 70, 229], // Indigo 600
      textColor: [255, 255, 255],
      fontSize: 8.5,
      fontStyle: 'bold',
      halign: 'left',
      cellPadding: 5,
    },
    bodyStyles: {
      fontSize: 8,
      textColor: [30, 41, 59],
      cellPadding: 4.5,
    },
    alternateRowStyles: {
      fillColor: [248, 250, 252],
    },
    columnStyles: {
      0: { cellWidth: 24, halign: 'center' },
      1: { cellWidth: 68 },
      2: { cellWidth: 55 },
      3: { cellWidth: 120, fontStyle: 'bold' },
      4: { cellWidth: 70 },
      5: { cellWidth: 46, halign: 'center' },
      6: { cellWidth: 70 },
      7: { cellWidth: 50, halign: 'center' },
      8: { cellWidth: 50, halign: 'center' },
      9: { cellWidth: 'auto' },
    },
    didDrawPage: (data) => {
      // Footer on every page
      const pageNumber = doc.internal.getNumberOfPages();
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8);
      doc.setTextColor(148, 163, 184);
      doc.text(
        `HEIMDALL Gate Records Archive — Official IIIT Pune Hostel Record — Confidential`,
        40,
        pageHeight - 20
      );
      doc.text(
        `Page ${pageNumber} of ${doc.internal.getNumberOfPages()}`,
        pageWidth - 90,
        pageHeight - 20
      );
    },
  });

  // Calculate safe file name
  const safePeriod = String(metadata.period || 'Records').replace(/[^a-zA-Z0-9_-]/g, '_');
  const filename = customFileName || `HEIMDALL_Gate_Records_${safePeriod}.pdf`;

  doc.save(filename);
};
